//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUAPULEMA_EXAMEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeActiviry
    {
        public int idEmpAct { get; set; }
        public int idEmployee { get; set; }
        public string employeeName { get; set; }
        public string activity { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string state { get; set; }
    }
}
